### ISSUE TITLE
Can't figure out how to run

### ISSUE THREAD

**Issue by tyvdh** [driftyco/ionic-horizon-chat-demo#1]
I'm looking into using Horizon on an existing Ionic app but I can't sort out how to get this project to run locally. Can you include some info in the README?

**Comment by ericb** [comment]
Currently this is just a playground-repo for us so we don't have any documentation with it specifically, but if you were just looking to see how we setup the connection to a horizon instance you can see that [here](https://github.com/driftyco/ionic-horizon-chat-demo/blob/e04c6509761414c221d5f9fd3c2a6426ba6ff43b/www/index.html) and [here](https://github.com/driftyco/ionic-horizon-chat-demo/blob/eec9884da3ac253a3ac2aa6d580524d98e27ff9d/app/pages/global/global.ts)

**Comment by tyvdh** [comment]
Ah gotcha. Well once you've got something for the masses be sure and hit me up!
